"""Bulk-insert leads gevonden via web search (Feb 2026 batch).

Run vanuit /app/backend:
    python -m scripts.import_web_search_leads

Idempotent: bestaande emails (case-insensitive) worden overgeslagen.
"""
import asyncio
import re
import sys
import uuid
from datetime import datetime, timezone

# zorg dat we modules uit /app/backend kunnen importeren
sys.path.insert(0, "/app/backend")

from database import db  # noqa: E402

EMAIL_RE = re.compile(r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')


# Verzameld via parallelle Google-searches op Feb 2026.
# Bron-bevestigd via .fr/.be/.de/.it dealer pagina's en BMW/Honda/Yamaha locators.
WEB_SEARCH_LEADS = [
    # ===== FRANKRIJK =====
    {"name": "Paris Est Moto", "email": "contact@paris-est-moto.fr", "city": "Champigny-sur-Marne",
     "website": "https://www.paris-est-moto.fr", "country": "FR", "notes": "Paris Est — moto dealer"},
    {"name": "RB Scooters Bastille", "email": "contact@rb-scooters.com", "city": "Paris",
     "website": "https://www.rb-scooters.com", "country": "FR", "notes": "Paris 11e — Zontes/scooter dealer"},
    {"name": "MekaBike Lyon", "email": "contact@mekabike.fr", "city": "Lyon",
     "website": "https://www.mekabike.fr", "country": "FR", "notes": "Lyon 3e — moto dealer"},
    {"name": "Moto Moretti", "email": "contact@motomoretti.fr", "city": "Marseille",
     "website": "https://motomoretti.fr", "country": "FR", "notes": "Marseille 7e"},
    {"name": "Urban Moto", "email": "contact@urbanmoto.fr", "city": "Marseille",
     "website": "https://urbanmoto.fr", "country": "FR", "notes": "Marseille 10e"},
    {"name": "JM Motors Marseille (Azur Scoot)", "email": "azurscoot13@gmail.com", "city": "Marseille",
     "website": "https://jmmotors.fr", "country": "FR", "notes": "Marseille 6e"},
    {"name": "Californie Moto", "email": "califmoto06@gmail.com", "city": "Nice", "postcode": "06300",
     "website": "https://californie-moto.com", "country": "FR", "notes": "CFMOTO dealer Nice"},
    {"name": "Nissa Motor", "email": "nissamotor@yahoo.fr", "city": "Nice", "postcode": "06000",
     "website": "https://www.nissamotor.fr", "country": "FR", "notes": "36 rue Lamartine, Nice"},
    {"name": "Ducati Nantes (BPM Motorbike)", "email": "contact-bpmmotorbike-nantes@bpmgroup.fr",
     "city": "Orvault", "postcode": "44700", "website": "https://bpmmotorbike.fr",
     "country": "FR", "notes": "350 Route de Vannes, Orvault — Ducati"},
    {"name": "BS2 Moto", "email": "bs2moto@gmail.com", "city": "Saint-Étienne-de-Montluc",
     "website": "https://bs2moto.fr", "country": "FR", "notes": "Tussen Nantes en Saint-Nazaire"},
    {"name": "Delahaye Motors", "email": "info@delahayemotors.fr", "city": "Labège",
     "website": "https://delahayemotors.fr", "country": "FR", "notes": "Toulouse / Labège"},
    {"name": "MT Motos", "email": "thierry@mt-moto.fr", "city": "Lille", "postcode": "59000",
     "website": "https://www.mt-moto.fr", "country": "FR", "notes": "15 Rue Gustave Delory, Lille"},
    {"name": "Rennes Motos", "email": "rennesmotos@hotmail.com", "city": "Vezin-le-Coquet",
     "postcode": "35132", "website": "https://rennesmotos.com", "country": "FR",
     "notes": "9 Rue du Lieutenant Colonel Dubois, Rennes-regio"},
    {"name": "Moto Labo", "email": "info@motolabo.fr", "city": "Échirolles", "postcode": "38130",
     "website": "https://www.motolabo.fr", "country": "FR", "notes": "2 Rue de Bretagne, Grenoble-regio"},
    {"name": "Altitude Moto (Honda Grenoble)", "email": "contact@altitude-moto.com",
     "city": "Grenoble", "website": "", "country": "FR", "notes": "Pôle Moto 38 / Honda Grenoble"},
    {"name": "Cyclo Services", "email": "cyclo.services@wanadoo.fr", "city": "Montpellier",
     "website": "https://cycloservicesmontpellier.fr", "country": "FR",
     "notes": "Peugeot scooters/moto Montpellier"},
    {"name": "VSP Motos", "email": "contact@vspmotos.fr", "city": "Reims",
     "website": "https://www.vspmotos.fr", "country": "FR",
     "notes": "Kawasaki/Suzuki/Benelli/Orcal/FB Mondial dealer Reims"},
    {"name": "Power NG", "email": "contact@powerng.fr", "city": "Cannes",
     "website": "https://www.powerng.fr", "country": "FR", "notes": "CFMOTO Cannes"},
    {"name": "Power 06", "email": "contact@power06.fr", "city": "Cannes",
     "website": "https://www.power06.fr", "country": "FR", "notes": "BSA dealer Cannes"},
    {"name": "Avignon Motors Group", "email": "j.tatry@suttelgroup.com", "city": "Avignon",
     "website": "", "country": "FR", "notes": "CFMOTO/Zontes Avignon (Suttel Group)"},
    {"name": "Technic Moto Annecy", "email": "magasin@technic-moto.fr", "city": "Meythet",
     "website": "https://www.technic-moto.fr", "country": "FR", "notes": "Kawasaki Annecy"},
    {"name": "BMW Motorrad Car Avenue Metz", "email": "contactsmoto@caravenue.net.bmw.fr",
     "city": "Metz", "website": "", "country": "FR", "notes": "BMW Motorrad Car Avenue Metz"},
    {"name": "Motomob", "email": "motomob@wanadoo.fr", "city": "Essey-lès-Nancy",
     "website": "https://www.motomob.fr", "country": "FR", "notes": "Nancy-regio"},
    {"name": "Motocity Besançon", "email": "charles@motocity.fr", "city": "Besançon",
     "website": "https://piaggiogroup.motocity.fr", "country": "FR", "notes": "Piaggio Group Besançon"},

    # ===== BELGIË =====
    {"name": "Moto's Goossens", "email": "info@motosgoossens.be", "city": "Oelegem",
     "website": "https://motosgoossens.be", "country": "BE", "notes": "Regio Antwerpen"},
    {"name": "Motorshop Gent", "email": "motogent@proximus.be", "city": "Merelbeke",
     "website": "https://motorshop-gent.be", "country": "BE", "notes": "Gent-regio"},
    {"name": "R4 Moto's Gent", "email": "info@r4motos.be", "city": "Gent",
     "website": "https://r4motos-gent.be", "country": "BE", "notes": "Gent"},
    {"name": "Bariseau Mottrie Brugge (Sales)", "email": "sales.brugge@bariseaumottrie.be",
     "city": "Brugge", "website": "https://www.bariseaumottrie.be", "country": "BE",
     "notes": "Sales — Garage Deboo Brugge"},
    {"name": "Bariseau Mottrie Brugge (Aftersales)", "email": "aftersales.brugge@bariseaumottrie.be",
     "city": "Brugge", "website": "https://www.bariseaumottrie.be", "country": "BE",
     "notes": "Aftersales — Garage Deboo Brugge"},
    {"name": "BMW Louyet Namur", "email": "namur@louyet.be", "city": "Wierde",
     "website": "https://louyet.bmw.be/fr/namur", "country": "BE", "notes": "BMW Motorrad Namur"},
    {"name": "JDC Moto", "email": "info@jdcmoto.be", "city": "Namur",
     "website": "https://www.jdcmoto.be", "country": "BE", "notes": "Namur moto dealer"},
    {"name": "MV Agusta Liège", "email": "info@mvagustaliege.be", "city": "Liège",
     "website": "https://mvagustaliege.be", "country": "BE", "notes": "MV Agusta Liège"},
    {"name": "Husqvarna Liège", "email": "info@husqvarnaliege.be", "city": "Liège",
     "website": "https://husqvarnaliege.be", "country": "BE", "notes": "Husqvarna dealer Liège"},
    {"name": "Harley-Davidson Mons", "email": "enzo-import@skynet.be", "city": "Mons-Cuesmes",
     "website": "https://harley-davidson-mons.be", "country": "BE", "notes": "Harley Mons"},
    {"name": "Louyet Motor Namur", "email": "namur@louyetmotor.be", "city": "Cognelée",
     "website": "https://louyetmotor.be/fr/namur", "country": "BE", "notes": "BMW Motorrad Louyet Namur"},
    {"name": "Louyet Motor Marcinelle", "email": "marcinelle@louyetmotor.be", "city": "Marcinelle",
     "website": "https://louyetmotor.be/fr/marcinelle", "country": "BE",
     "notes": "Charleroi/Marcinelle — BMW Motorrad"},
    {"name": "Sprimont 2 Roues", "email": "info@sprimont2roues.be", "city": "Sprimont",
     "website": "https://www.sprimont2roues.be", "country": "BE", "notes": "Liège-regio"},
    {"name": "Moto Zenith", "email": "info@motozenith.be", "city": "Ben Ahin",
     "website": "https://www.motozenith.be", "country": "BE", "notes": "Bij Huy / Liège"},
    {"name": "Aankoopmotoren.be", "email": "info@aankoopmotoren.be", "city": "Kortrijk",
     "website": "https://www.aankoopmotoren.be", "country": "BE", "notes": "Kortrijk motor-aankoop"},
    {"name": "Action Sports Verviers", "email": "info@actionsports.be", "city": "Verviers",
     "website": "https://b2b.actionsports.be", "country": "BE", "notes": "Verviers"},
    {"name": "Triumph Moto Visé", "email": "info@moto-vise.be", "city": "Visé",
     "website": "https://www.triumph-moto-vise.be", "country": "BE", "notes": "Triumph dealer Liège-regio"},

    # ===== DUITSLAND =====
    {"name": "Motorrad Merkel", "email": "info@motorradmerkel.de", "city": "München",
     "website": "https://www.motorradmerkel.de", "country": "DE", "notes": "München moto dealer"},
    {"name": "Wimmer und Merkel", "email": "info@wum-muc.de", "city": "München",
     "website": "https://www.motorrad-wimmer-merkel.de", "country": "DE", "notes": "München"},
    {"name": "Fuhrmann Motor Berlin", "email": "info@fuhrmann-motor.de", "city": "Berlin",
     "website": "https://www.fuhrmann-motor.de", "country": "DE", "notes": "Berlin moto dealer"},
    {"name": "Ducati Berlin", "email": "kontakt@ducati-berlin.de", "city": "Berlin",
     "website": "https://ducati-berlin.de", "country": "DE", "notes": "Ducati dealer Berlin"},
    {"name": "Yamaha Zentrum Berlin", "email": "kontakt@yamaha-zentrum.berlin", "city": "Berlin",
     "website": "", "country": "DE", "notes": "Yamaha Berlin"},
    {"name": "Heuser Motorräder", "email": "mail@heuser-motorraeder.de", "city": "Hamburg",
     "website": "https://heuser-motorraeder.de", "country": "DE", "notes": "Hamburg moto dealer"},
    {"name": "Triumph Hamburg", "email": "janine@triumph-hamburg.de", "city": "Hamburg",
     "website": "https://triumph-hamburg.de", "country": "DE", "notes": "Triumph Hamburg"},
    {"name": "MCA Frankfurt", "email": "info@mca-frankfurt.de", "city": "Frankfurt",
     "website": "https://www.mca-motorrad.de", "country": "DE", "notes": "Frankfurt moto dealer"},
    {"name": "H.M. Motorradhaus Frankfurt", "email": "info@hm-motorradhaus.de", "city": "Frankfurt",
     "website": "https://husqvarna-frankfurt.de", "country": "DE",
     "notes": "Husqvarna Frankfurt / Allround vermietung"},
    {"name": "StuteHengst Köln", "email": "info@stutehengst.de", "city": "Köln", "postcode": "51103",
     "website": "https://stutehengst.de", "country": "DE", "notes": "BMW Motorrad Köln"},
    {"name": "BMW Motorrad Stuttgart", "email": "motorrad-stuttgart@bmw.de", "city": "Stuttgart",
     "postcode": "70569", "website": "https://www.bmw-stuttgart.de", "country": "DE",
     "notes": "BMW Motorrad Zentrum Stuttgart"},
    {"name": "BMW Niederlassung Hannover", "email": "nl-hannover@bmw.de", "city": "Hannover",
     "postcode": "30539", "website": "https://www.bmw-hannover.de", "country": "DE",
     "notes": "BMW Motorrad Hannover"},
    {"name": "BMW Motorrad Hannover Service", "email": "motorradservice.hannover@bmw.de",
     "city": "Hannover", "postcode": "30539", "website": "https://www.bmw-hannover.de",
     "country": "DE", "notes": "Service-afdeling"},
    {"name": "Motorrad Huchting", "email": "info@motorrad-huchting.de", "city": "Bremen",
     "postcode": "28259", "website": "https://www.motorrad-huchting.de", "country": "DE",
     "notes": "Bremen moto dealer"},

    # ===== ITALIË (extra naast bestaande seed) =====
    {"name": "DG Moto", "email": "dgmotosrl@gmail.com", "city": "Roma", "postcode": "00152",
     "website": "https://www.dgmoto.it", "country": "IT",
     "notes": "Circonvallazione Gianicolense 204A, Roma"},
    {"name": "DVMoto Roma", "email": "info@dvmoto.it", "city": "Roma", "postcode": "00154",
     "website": "https://dvmoto.it", "country": "IT", "notes": "Via del Porto Fluviale 13-19, Roma"},
    {"name": "Giovanelli Moto Milano", "email": "info@giovanellimoto.it", "city": "Milano",
     "website": "https://www.giovanellimoto.it", "country": "IT", "notes": "Milano moto dealer"},
    {"name": "Tamburrino Moto", "email": "info@tamburrinomoto.it", "city": "Napoli", "postcode": "80143",
     "website": "https://tamburrinomoto.ligier.it", "country": "IT",
     "notes": "Via Nuova Poggioreale 159, Napoli"},
    {"name": "Moto Megaride", "email": "motomegaride@gmail.com", "city": "Napoli", "postcode": "80122",
     "website": "https://www.motomegaride.it", "country": "IT", "notes": "Via Francesco Giordani, Napoli"},
    {"name": "Lamberti Moto Napoli", "email": "info@lambertimoto.it", "city": "Napoli",
     "website": "https://lambertimoto.it", "country": "IT", "notes": "Via Nuova Del Campo 25/C"},
    {"name": "Quattrocchi Moto", "email": "info@quattrocchimoto.it", "city": "Torino",
     "website": "https://www.quattrocchimoto.it", "country": "IT", "notes": "Via Capelli 100, Torino"},
    {"name": "Harley-Davidson Torino", "email": "info@harley-davidson-torino.it", "city": "Torino",
     "website": "https://harley-davidson-torino.it", "country": "IT", "notes": "Harley Torino"},
    {"name": "Nova Moto Firenze", "email": "info@novamoto.it", "city": "Firenze",
     "website": "https://www.bmw-motorrad.it/novamoto-firenze", "country": "IT",
     "notes": "BMW Motorrad Firenze - Via Pratese 169"},
    {"name": "Motolandia Verona", "email": "info@motolandiasrl.com", "city": "Verona",
     "website": "https://www.motolandiasrl.com", "country": "IT", "notes": "Via Roveggia 79/B, Verona"},
    {"name": "CMTmotor Genova", "email": "genova.orsini@cmtmotor.com", "city": "Genova",
     "website": "https://www.cmtmotor.com", "country": "IT", "notes": "Via Orsini 58R, Genova"},
    {"name": "Ponente Moto", "email": "erika@ponentemoto.com", "city": "Genova",
     "website": "https://ponentemoto.it", "country": "IT", "notes": "Via Giacomo Puccini, Genova"},
    {"name": "Moto Service Bari", "email": "info@motoservice-bari.it", "city": "Bari",
     "website": "https://motoservice-foggia.it/sede-bari", "country": "IT", "notes": "Bari dealer"},
    {"name": "Gambino Moto Academy", "email": "yamaha.info@gambinomoto.it", "city": "Palermo",
     "website": "https://www.gambinomoto.it", "country": "IT", "notes": "Yamaha Palermo"},
    {"name": "Hobby Moto Catania", "email": "info@hobby-moto.it", "city": "Catania",
     "website": "http://www.hobbymoto.it", "country": "IT", "notes": "Catania moto dealer"},
    {"name": "Valeriano Moto Catania", "email": "valeriano1983@live.it", "city": "Catania",
     "website": "https://www.valerianomoto.it", "country": "IT", "notes": "Catania"},
    {"name": "Almia Motors Cagliari", "email": "info@almiamotors.it", "city": "Cagliari",
     "website": "https://www.almiamotors.it", "country": "IT", "notes": "Cagliari moto dealer"},

    # ===== Batch 2 (Feb 2026 — extra Google searches) =====
    # FR — extra steden
    {"name": "Motoman Quimper", "email": "compta@motoman-shop.fr", "city": "Quimper",
     "website": "https://www.motoman-shop.fr", "country": "FR", "notes": "Bretagne / Yamaha"},
    {"name": "Docteur Scooter", "email": "docteur-scooter@orange.fr", "city": "Perpignan",
     "website": "", "country": "FR", "notes": "Scooter/moto Perpignan"},
    {"name": "Le Garage Béziers (Zontes)", "email": "legarage2@bbox.fr", "city": "Béziers",
     "website": "", "country": "FR", "notes": "Zontes dealer Béziers"},
    {"name": "Motoland Amiens (Honda)", "email": "julien.r@motoland.eu", "city": "Rivery",
     "website": "https://amiens.honda-motos.com", "country": "FR", "notes": "Honda Amiens-regio"},
    {"name": "Moto & Co Beauvais", "email": "sebastien@motoandco.fr", "city": "Beauvais",
     "website": "https://piaggio-beauvais.com", "country": "FR", "notes": "Piaggio Beauvais"},
    {"name": "Eden Motors", "email": "contact@eden-motors.fr", "city": "Compiègne",
     "website": "https://www.eden-motors.fr", "country": "FR", "notes": "Compiègne moto dealer"},
    # BE — extra
    {"name": "LM Motors", "email": "info@lmmotors.be", "city": "Vlamertinge",
     "website": "https://www.lmmotors.be", "country": "BE", "notes": "West-Vlaanderen (bij Ieper)"},
    # IT — extra
    {"name": "Indian Moto Padova", "email": "info@indianmoto-padova.it", "city": "Padova",
     "website": "https://indianmoto-padova.it", "country": "IT", "notes": "Indian Motorcycle Padova"},
    {"name": "Ferali Moto", "email": "info@feralimoto.it", "city": "Padova",
     "website": "https://feralimoto.it", "country": "IT", "notes": "Padova moto"},
    {"name": "Top Motor Modena", "email": "info@topmotor.it", "city": "Modena",
     "website": "https://www.topmotor.it", "country": "IT", "notes": "Modena dealer"},
    {"name": "Franchini e Alpinoli Honda Modena", "email": "franchiniealpinoli@hondaitalia.com",
     "city": "Modena", "website": "https://www.franchiniealpinoli.it", "country": "IT",
     "notes": "Honda dealer Modena"},
    {"name": "Triumph Bologna", "email": "service@triumphbologna.it", "city": "Bologna",
     "website": "https://www.triumphbologna.it", "country": "IT", "notes": "Triumph Bologna"},

    # ===== Batch 3 (Feb 2026 — derde scrape ronde) =====
    # FR Le Havre — Pôle de la Moto cluster (1 dealergroep, 6 emails per merk)
    {"name": "Pôle de la Moto Le Havre", "email": "contact@poledelamoto.fr",
     "city": "Gonfreville-l'Orcher", "website": "https://poledelamoto.fr",
     "country": "FR", "notes": "Multi-merk dealer Le Havre"},
    {"name": "Yamaha Le Havre (M2)", "email": "contact@m2-lehavre.fr",
     "city": "Gonfreville-l'Orcher", "website": "https://poledelamoto.fr",
     "country": "FR", "notes": "Yamaha Le Havre"},
    {"name": "Suzuki Le Havre (Bazar de la Bécane)", "email": "bazardelabecane@poledelamoto.fr",
     "city": "Gonfreville-l'Orcher", "website": "https://poledelamoto.fr",
     "country": "FR", "notes": "Suzuki Le Havre"},
    {"name": "Kawasaki Le Havre (K-Bike)", "email": "contact-kbike@gmail.com",
     "city": "Gonfreville-l'Orcher", "website": "", "country": "FR", "notes": "Kawasaki Le Havre"},
    {"name": "Polaris Le Havre", "email": "remy.hauters@poledelamoto.fr",
     "city": "Gonfreville-l'Orcher", "website": "https://poledelamoto.fr",
     "country": "FR", "notes": "Polaris Le Havre"},
    {"name": "Maxxess Le Havre", "email": "maxxesslh@gmail.com",
     "city": "Gonfreville-l'Orcher", "website": "", "country": "FR", "notes": "Maxxess Le Havre"},
    {"name": "Moto Transfert Aix", "email": "contact@mototransfert.fr", "city": "Aix-en-Provence",
     "website": "https://www.mototransfert.fr", "country": "FR", "notes": "Aix-en-Provence"},
    {"name": "Speedway Toulon La Garde", "email": "garde@speedway.fr", "city": "La Garde",
     "website": "https://www.speedway.fr", "country": "FR", "notes": "Toulon-regio Speedway"},
    # IT extra
    {"name": "Vicenza Moto", "email": "info@vicenzamoto.com", "city": "Vicenza",
     "website": "https://www.vicenzamoto.com", "country": "IT", "notes": "Vicenza moto dealer"},
    {"name": "Biemme Moto Trento", "email": "info@biemmemoto.net", "city": "Trento",
     "website": "https://www.biemmemoto.net", "country": "IT", "notes": "Trento moto dealer"},
    {"name": "Centro Auto Trieste", "email": "info@centroautotrieste.it", "city": "Trieste",
     "website": "https://www.centroautotrieste.it", "country": "IT", "notes": "Trieste"},
    {"name": "Delta Motors Ancona", "email": "info@delta-motors.it", "city": "Ancona",
     "postcode": "60131", "website": "https://www.delta-motors.it", "country": "IT",
     "notes": "Via Luigi Albertini 26, Ancona"},
    {"name": "Tortora Moto Salerno", "email": "info@tortoramoto.it", "city": "Salerno",
     "postcode": "84131", "website": "", "country": "IT",
     "notes": "Via Roberto Wenner 31/33, Salerno"},
    {"name": "Rosciano Moto Salerno", "email": "info@roscianomoto.it", "city": "Salerno",
     "website": "http://roscianomoto.it", "country": "IT", "notes": "Via Cappello Vecchio 17, Salerno"},
    {"name": "Dea Moto Cremona", "email": "info@deamotocremona.it", "city": "Cremona",
     "website": "", "country": "IT", "notes": "Cremona moto dealer"},
    {"name": "Officina FG Moto Ravenna", "email": "info@fgmoto.it", "city": "Ravenna",
     "website": "", "country": "IT", "notes": "Ravenna moto-officina"},
    # BE extra
    {"name": "Moto6", "email": "info@motosix.be", "city": "België",
     "website": "https://motosix.be", "country": "BE", "notes": "Yamaha specialist"},
    {"name": "BMW Pautric Woluwe", "email": "info.woluwe@pautric.be", "city": "Woluwe",
     "website": "https://www.pautric.bmw.be", "country": "BE", "notes": "BMW Motorrad Brussel"},
    {"name": "BMW Pautric Drogenbos", "email": "info.drogenbos@pautric.be", "city": "Drogenbos",
     "website": "https://www.pautric.bmw.be", "country": "BE", "notes": "BMW Motorrad Drogenbos"},

    # ===== Batch 4 (Feb 2026 — EU-breed: CH/AT/LU/PL/CZ/ES + extras) =====
    # Frankrijk extra
    {"name": "Moto Plaisir Annemasse", "email": "contact@moto-plaisir.fr", "city": "Ville-la-Grand",
     "website": "https://www.moto-plaisir.fr", "country": "FR", "notes": "Haute-Savoie"},
    {"name": "GCA Alençon", "email": "contact@groupegca.com", "city": "Alençon",
     "website": "https://www.toyota.fr/reseau", "country": "FR", "notes": "Groupe GCA"},
    # Zwitserland (CH)
    {"name": "Autoverkehr Bern BMW Motorrad", "email": "motorrad@bern.autoverkehr.ch", "city": "Bern",
     "website": "https://autoverkehr.ch", "country": "CH", "notes": "BMW Motorrad partner Bern"},
    {"name": "Moto Rush SA Genève", "email": "info@motorush.ch", "city": "Genève",
     "postcode": "1205", "website": "", "country": "CH", "notes": "Bd de la Cluse 9-11, Genève"},
    {"name": "BMW Motorrad Genève-Meyrin (Facchinetti)", "email": "motos-ge@facchinetti.ch",
     "city": "Meyrin", "website": "", "country": "CH", "notes": "BMW Motorrad Facchinetti"},
    {"name": "Moto Passion SA Renens", "email": "info@motopassion.ch", "city": "Renens",
     "postcode": "1020", "website": "https://www.motopassion.ch", "country": "CH",
     "notes": "Lausanne-regio"},
    # Oostenrijk (AT)
    {"name": "Euro Motors Graz", "email": "verkauf@euromotorsgraz.at", "city": "Graz",
     "postcode": "8053", "website": "https://euromotorsgraz.at", "country": "AT",
     "notes": "Harter Straße 70, Graz"},
    {"name": "Motorrad Klug GmbH Graz", "email": "office@klug.at", "city": "Graz",
     "postcode": "8053", "website": "https://www.klug.at", "country": "AT",
     "notes": "Harter Straße 94, Graz"},
    # Luxemburg (LU)
    {"name": "ATR Buschdorf", "email": "info@atr.lu", "city": "Buschdorf",
     "postcode": "L-7418", "website": "", "country": "LU",
     "notes": "3A Op Rommelspont — moto workshop+sales"},
    # Polen (PL)
    {"name": "Honda MCS Warszawa", "email": "info@mcsonline.pl", "city": "Warszawa",
     "postcode": "01-424", "website": "https://hondamcs.pl", "country": "PL",
     "notes": "Honda dealer Warszawa - Al. Prymasa Tysiąclecia 76H"},
    {"name": "MotoMotion Warszawa", "email": "info@motomotion.pl", "city": "Warszawa",
     "website": "https://www.motomotion.pl", "country": "PL",
     "notes": "Honda/Kawasaki/Suzuki/Yamaha multi-merk"},
    {"name": "RPM Motocykle Wrocław", "email": "rpmmotocykle@rpmmotocykle.pl",
     "city": "Wrocław", "postcode": "51-423", "website": "https://www.rpmmotocykle.pl",
     "country": "PL", "notes": "Honda dealer Wrocław"},
    # Tsjechië (CZ)
    {"name": "City Moto Plzeň", "email": "info@citymoto.cz", "city": "Plzeň",
     "website": "https://www.citymoto.cz", "country": "CZ", "notes": "Plzeň motor dealer"},
    {"name": "Harness Praha", "email": "info@harnessbike.com", "city": "Praha",
     "website": "https://harnessbike.com", "country": "CZ", "notes": "Praha 10 motor dealer"},
    {"name": "ACUT Moto Praha", "email": "info@acutmoto.cz", "city": "Praha",
     "website": "", "country": "CZ", "notes": "Benda Motor Praha dealer"},
    {"name": "ATVA Brno", "email": "brno@atvamoto.cz", "city": "Brno",
     "website": "https://www.swm-motor.cz", "country": "CZ", "notes": "SWM dealer Brno"},
    # Spanje (ES)
    {"name": "Motor Quad Zaragoza", "email": "zaragoza@motorquad.com", "city": "Zaragoza",
     "postcode": "50197", "website": "https://www.polariszaragoza.es", "country": "ES",
     "notes": "Indian Motorcycle Zaragoza"},
    # Italië extra
    {"name": "HD Motor Messina", "email": "info@hdmotor.it", "city": "Messina",
     "website": "http://www.hdmotor.it", "country": "IT", "notes": "Messina Sicilia"},
    {"name": "Lallo Moto Sassari", "email": "lallomoto2017@libero.it", "city": "Sassari",
     "website": "https://www.lallomoto.it", "country": "IT", "notes": "Sardegna"},
    {"name": "Pastri Motors", "email": "info@pastrimotors.it", "city": "Chianciano Terme",
     "website": "https://www.pastrimotors.it", "country": "IT",
     "notes": "Toscana — Siena provincie"},
    # Duitsland extra
    {"name": "Motorsport Service Kiel", "email": "info@motorsport-kiel.de", "city": "Kiel",
     "postcode": "24159", "website": "https://www.motorsport-kiel.de", "country": "DE",
     "notes": "Friedrichsorter Str. 29, Kiel"},
    {"name": "Schubert Motors Magdeburg", "email": "info@schubert-motors.de", "city": "Magdeburg",
     "postcode": "39108", "website": "https://www.schubert-motors.de", "country": "DE",
     "notes": "BMW Motorrad Zentrum Magdeburg"},
    {"name": "Triumph Magdeburg", "email": "info@triumph-magdeburg.de", "city": "Magdeburg",
     "postcode": "39128", "website": "https://www.triumph-magdeburg.de", "country": "DE",
     "notes": "Triumph Magdeburg"},

    # ===== Batch 5 (Feb 2026 — NL noord+oost + DE Süd + FR west) =====
    # Nederland (extra naast motoroccasion seed)
    {"name": "TT Motoren Zwolle", "email": "info@ttmotoren.nl", "city": "Zwolle",
     "postcode": "8013 PD", "website": "https://www.ttmotoren.nl", "country": "NL",
     "notes": "Suzuki & Kawasaki dealer — Marsweg 1"},
    {"name": "AE Motorbikes Zwolle", "email": "info@aemotorbikes.nl", "city": "Zwolle",
     "website": "https://aemotorbikes.nl", "country": "NL", "notes": "Curieweg 18, Zwolle"},
    {"name": "Motorhuis Zwolle", "email": "info@motorhuiszwolle.nl", "city": "Zwolle",
     "postcode": "8013 NL", "website": "https://www.motorhuiszwolle.nl", "country": "NL",
     "notes": "George Stephensonstraat 5"},
    {"name": "Blauweplaat Motoren", "email": "info@blauweplaat.nl", "city": "Veldhoven",
     "website": "https://www.blauweplaat.nl", "country": "NL",
     "notes": "Klassieke Honda viercilinders"},
    # Duitsland Süd
    {"name": "2Radzentrum Karlsruhe", "email": "info@2radzentrum-karlsruhe.de", "city": "Karlsruhe",
     "website": "", "country": "DE", "notes": "Motorradhändler Karlsruhe"},
    {"name": "Motorradzentrum Backes Mainz", "email": "info@motorradzentrum-backes.de",
     "city": "Budenheim", "website": "", "country": "DE", "notes": "Suzuki dealer Mainz-regio"},
    {"name": "Motorland Mannheim", "email": "info@motorland-zweirad.de", "city": "Mannheim",
     "website": "https://www.motorland-zweirad.de", "country": "DE",
     "notes": "Motorland Motorrad GmbH"},
    # Frankrijk West
    {"name": "TCS Motos Cholet", "email": "contact@tcsmotos.fr", "city": "Cholet",
     "website": "https://tcsmotos.fr", "country": "FR", "notes": "Proche Cholet 49"},
    {"name": "Advance 3000 Cholet", "email": "pieceadvance@gmail.com", "city": "Cholet",
     "website": "https://www.cf-moto.fr", "country": "FR", "notes": "CFMOTO dealer Cholet"},
    {"name": "Dafy Moto Niort", "email": "niort@dafy-moto.fr", "city": "Niort",
     "postcode": "79000", "website": "", "country": "FR", "notes": "Niort dealer"},
    # België West-Vlaanderen + Limburg
    {"name": "Mcmoto Meulebeke", "email": "info@mcmoto.be", "city": "Meulebeke",
     "website": "https://www.mcmoto.be", "country": "BE", "notes": "Tweedehands motoren"},
    {"name": "Felix & Jos Hasselt", "email": "info@felix-jos.be", "city": "Hasselt",
     "website": "https://www.felix-jos.be", "country": "BE",
     "notes": "Honda & CFMOTO dealer Hasselt"},

    # ===== Batch 6 (Feb 2026 — laatste mega-batch) =====
    # NL extra
    {"name": "Arie Molenaar Motors Utrecht", "email": "info@ariemolenaarmotors.nl",
     "city": "Utrecht", "website": "https://www.ariemolenaarmotors.nl", "country": "NL",
     "notes": "Utrecht motorzaak"},
    {"name": "Joost Motoren Utrecht", "email": "info@joostmotoren.nl", "city": "Utrecht",
     "website": "https://www.joostmotoren.nl", "country": "NL", "notes": "Utrecht"},
    {"name": "Hofland Motoren Amersfoort", "email": "info@hoflandmotoren.nl", "city": "Amersfoort",
     "website": "", "country": "NL", "notes": "Amersfoort"},
    # DE Süd / Mitte
    {"name": "Motorrad Eder Augsburg", "email": "info@motorrad-eder.de", "city": "Augsburg",
     "website": "https://motorrad-eder.de", "country": "DE", "notes": "Augsburg"},
    {"name": "Triumph Augsburg (Dörr Bike)", "email": "info@triumphaugsburg.de",
     "city": "Augsburg", "website": "https://triumphaugsburg.de", "country": "DE",
     "notes": "Triumph Augsburg"},
    {"name": "MATKO-MOTO Augsburg", "email": "info@matko-moto.de", "city": "Augsburg",
     "website": "https://matko-moto.de", "country": "DE", "notes": "Motorradhandel + Coaching"},
    {"name": "MotoPro Augsburg", "email": "info@moto-pro.de", "city": "Augsburg",
     "website": "https://www.moto-pro.de", "country": "DE", "notes": "Augsburg dealer"},
    {"name": "Sandner Motorradteile Regensburg", "email": "info@motorradteile-regensburg.de",
     "city": "Regensburg", "website": "https://www.motorradteile-regensburg.de",
     "country": "DE", "notes": "Regensburg parts+sales"},
    {"name": "Motorradhaus Stahl Würzburg", "email": "info@motorradhaus-stahl.de",
     "city": "Würzburg", "website": "https://www.motorradhaus-stahl.de", "country": "DE",
     "notes": "Würzburg dealer"},
    {"name": "AF Motobikes Heidelberg", "email": "info@af-motobikes.de", "city": "Heidelberg",
     "website": "", "country": "DE", "notes": "Heidelberg motorrad"},
    {"name": "PAQURO SYM Heidelberg", "email": "info@paquro.de", "city": "Heidelberg",
     "website": "https://www.paquro.de", "country": "DE", "notes": "SYM Motorroller Center"},
    # FR Sud
    {"name": "CC Motors Sète", "email": "ccmotorssete@hotmail.com", "city": "Sète",
     "postcode": "34200", "website": "https://cc-motors.fr", "country": "FR",
     "notes": "1 Rue de Bruxelles, Sète"},
    {"name": "Race Moto Nîmes (KTM)", "email": "contact@ktm-nimes.com", "city": "Nîmes",
     "postcode": "30900", "website": "https://www.zontes.fr", "country": "FR",
     "notes": "KTM dealer Nîmes - 275 rue John Mac Adam"},
    {"name": "Kawa Nîmes", "email": "commercial@kawa-nimes.fr", "city": "Nîmes",
     "website": "https://kawasaki-nimes.fr", "country": "FR", "notes": "Kawasaki Nîmes"},
    # BE extra
    {"name": "Stock Ath", "email": "info@stock-ath.be", "city": "Irchonwelz",
     "website": "https://www.stock-ath.be", "country": "BE",
     "notes": "Moto-pieces/scooter Ath-regio"},

    # ===== Batch 7 (Feb 2026 — DE+NL extra) =====
    {"name": "Hänsle Motorradsport", "email": "info@haensle.de", "city": "Freiburg",
     "website": "https://www.haensle.de", "country": "DE",
     "notes": "BMW/Kawasaki/Triumph/Zero dealer Freiburg-Offenburg"},
    {"name": "Bolman Motoren Den Haag", "email": "info@bolmanmotoren.nl", "city": "Den Haag",
     "website": "https://bolmanmotoren.nl", "country": "NL", "notes": "Den Haag motorzaak"},
    {"name": "Motor City Amsterdam", "email": "info@motorcityamsterdam.nl", "city": "Amsterdam",
     "website": "https://motorcityamsterdam.nl", "country": "NL",
     "notes": "Yamaha/Kawasaki/Suzuki/Royal Enfield/CF Moto/Can-Am"},
    {"name": "MotoPort Almere", "email": "info@motoportalmere.nl", "city": "Almere",
     "website": "https://www.motoport.nl", "country": "NL",
     "notes": "Suzuki/Moto Morini/QJMOTOR officieel dealer"},

    # ===== Batch 8 (Feb 2026 — final) =====
    {"name": "Mansour Motorradtechnik", "email": "info@mansour.de", "city": "Düsseldorf",
     "website": "https://www.mansour.de", "country": "DE", "notes": "Düsseldorf werkstatt+sales"},
    {"name": "Bikers Essen", "email": "info@bikers-essen.de", "city": "Mülheim",
     "website": "http://www.fahrschule-bikers.de", "country": "DE", "notes": "Essen-regio motorshop"},

    # ===== Batch 9 (Feb 2026 — DEEP DIVE DUITSLAND alle Bundesländer) =====
    {"name": "BMW Motorrad Zentrum Nürnberg", "email": "motorrad.nuernberg@bmw.de",
     "city": "Nürnberg", "postcode": "90441", "website": "https://www.bmw-motorrad.de/nuernberg",
     "country": "DE", "notes": "Max-Ottenstein-Str. 1"},
    {"name": "Harley-Davidson Nürnberg", "email": "info@harley-nuernberg.de",
     "city": "Nürnberg", "postcode": "90471", "website": "https://harley-nuernberg.de",
     "country": "DE", "notes": "Kreuzburger Straße 1"},
    {"name": "Motorpark Schrembs Bayreuth", "email": "info@motorpark-schrembs.de",
     "city": "Bayreuth", "postcode": "95448", "website": "https://www.motorpark-schrembs.de",
     "country": "DE", "notes": "Kawasaki Bayreuth"},
    {"name": "EMG-Eickmeyer Bielefeld", "email": "info@emg-eickmeyer.de", "city": "Bielefeld",
     "website": "https://emg-eickmeyer.de", "country": "DE", "notes": "Kawasaki + Verleih"},
    {"name": "Heartbeat-Bikes Mönchengladbach", "email": "info@heartbeat-bikes.de",
     "city": "Mönchengladbach", "website": "", "country": "DE", "notes": "Mönchengladbach"},
    {"name": "Motorradzentrum Offenbach", "email": "info@mz-offenbach.de",
     "city": "Heusenstamm", "website": "https://motorradzentrumoffenbach.de",
     "country": "DE", "notes": "Frankfurt-regio"},
    {"name": "Zweiradhaus Wieseck Gießen", "email": "info@zweiradhaus-wieseck.de",
     "city": "Gießen", "website": "https://www.zweiradhaus-wieseck.de", "country": "DE",
     "notes": "Kawasaki Gießen"},
    {"name": "Motorrad Center Darmstadt", "email": "info@motorradcenter-darmstadt.de",
     "city": "Darmstadt", "website": "https://www.motorradcenter-darmstadt.de",
     "country": "DE", "notes": "Darmstadt center"},
    {"name": "HD Oldenburg (Börjes Bikers)", "email": "info@hd-oldenburg.de",
     "city": "Oldenburg", "website": "https://www.hd-oldenburg.de", "country": "DE",
     "notes": "Harley Oldenburg"},
    {"name": "Dobbert Motorräder Wolfsburg", "email": "info@heiko-dobbert.de",
     "city": "Wolfsburg", "website": "https://heiko-dobbert.de", "country": "DE",
     "notes": "Wolfsburg"},
    {"name": "Ducati Wolfsburg", "email": "info@ducati-wolfsburg.de", "city": "Wolfsburg",
     "website": "https://www.autohaus-wolfsburg.de", "country": "DE",
     "notes": "Autohaus Wolfsburg Ducati"},
    {"name": "Triumph Leipzig (Klingenberger Kehl)", "email": "mail@triumph-leipzig.de",
     "city": "Leipzig", "postcode": "04103", "website": "https://www.triumph-leipzig.de",
     "country": "DE", "notes": "Zwickauer Straße 50"},
    {"name": "Wild East Motorcycles Chemnitz", "email": "mail@wildeastmotorcycles.de",
     "city": "Chemnitz", "postcode": "09120", "website": "https://www.wildeastmotorcycles.de",
     "country": "DE", "notes": "Indian Motorcycle Chemnitz"},
    {"name": "Motorrad Hermann Zwickau", "email": "info@motorrad-hermann.de",
     "city": "Zwickau", "website": "https://www.motorrad-hermann.de", "country": "DE",
     "notes": "Triumph Zwickau"},
    {"name": "Böning Motorräder Koblenz", "email": "info@boening.de", "city": "Koblenz",
     "website": "https://www.boening.de", "country": "DE", "notes": "Koblenz dealer"},
    {"name": "Motorradankauf Saarland", "email": "info@motorradankauf-saarland.de",
     "city": "Saarbrücken", "website": "https://www.motorradankauf-saarland.de",
     "country": "DE", "notes": "Saarbrücken motor-ankauf"},
    {"name": "Ducati Saarland (Moto Mondiale)", "email": "info@ducatisaarland.de",
     "city": "Saarbrücken", "website": "https://www.ducatisaarland.de", "country": "DE",
     "notes": "Ducati Saarland"},
    {"name": "Motorradshop Ahlers Potsdam", "email": "info@motorradshop-ahlers.de",
     "city": "Potsdam", "website": "https://www.motorradshop-ahlers.de", "country": "DE",
     "notes": "Potsdam motorshop"},

    # ===== Batch 10 (Feb 2026 — DE Nord + IT regio's) =====
    {"name": "MF-Performance Lübeck", "email": "info@mf-performance.de", "city": "Lübeck",
     "website": "https://mf-performance.de", "country": "DE", "notes": "Lübeck performance"},
    {"name": "Motorrad Ruser", "email": "info@motorrad-ruser.de", "city": "Schleswig-Holstein",
     "website": "https://yamaha-suedholstein.de", "country": "DE", "notes": "Yamaha Süd-Holstein"},
    {"name": "Raudzus Motorrad Husum", "email": "info@raudzus.de", "city": "Husum",
     "website": "https://www.raudzus.de", "country": "DE", "notes": "Husum motor dealer"},
    {"name": "Motorrad Hafenstein Rostock", "email": "werkstatt@motorrad-hafenstein.de",
     "city": "Rostock", "website": "https://motorrad-hafenstein.de", "country": "DE",
     "notes": "Rostock werkstatt"},
    # IT extra
    {"name": "Triumph Alessandria (BiAuto)", "email": "info@biautogroup.com",
     "city": "Alessandria", "postcode": "15122", "website": "https://www.triumphalessandria.it",
     "country": "IT", "notes": "Spinetta Marengo, Alessandria"},
    {"name": "Motorando Massa", "email": "info@motorando.com", "city": "Massa",
     "website": "https://cfmotoitaly.it", "country": "IT", "notes": "CFMOTO Toscana"},
    {"name": "Moto Shop 2000 Caserta", "email": "info@motoshop2000.com", "city": "Caserta",
     "website": "https://www.gruppodemichele.it", "country": "IT",
     "notes": "BMW/Ducati/KTM/Aprilia/Moto Guzzi"},
    {"name": "Speed Motor Campobasso", "email": "speed.motor@hotmail.it", "city": "Campobasso",
     "website": "https://www.speedmotorcampobasso.it", "country": "IT",
     "notes": "Honda Molise"},
    {"name": "Zeus Bike Forlì", "email": "info@zeusbike.it", "city": "Forlì",
     "website": "https://zeusbike.it", "country": "IT", "notes": "Via Balzella 67/B"},
    {"name": "Blue Bike Reggio Emilia", "email": "info@bluebike-re.it", "city": "Reggio Emilia",
     "website": "https://www.bluebike-re.it", "country": "IT",
     "notes": "Via Hiroshima 24/26"},
    {"name": "Desmo Corse Cesena", "email": "info@desmocorsecesena.it", "city": "Cesena",
     "website": "https://www.desmocorsecesena.it", "country": "IT",
     "notes": "Ducati officina Cesena"},

    # ===== Batch 11 (Feb 2026 — FR Bourgogne + BE Wallonie) =====
    {"name": "DMD Racing", "email": "info@dmdracing.be", "city": "Mons",
     "website": "https://www.dmdracing.be", "country": "BE",
     "notes": "Vespa/Piaggio Mons/La Louvière/Charleroi"},
    {"name": "KSMoto La Louvière", "email": "info@ksmoto.be", "city": "La Louvière",
     "website": "https://www.ksmoto.be", "country": "BE", "notes": "Moto dealer La Louvière"},
    {"name": "Motodoc Limal", "email": "info@motodoc.be", "city": "Limal",
     "website": "https://motodoc.be", "country": "BE", "notes": "Vente/achat motos Wallonie"},

    # ===== Batch 12 (Feb 2026 — DE deep city coverage) =====
    {"name": "MPD Moto Pabst Düsseldorf", "email": "info@motopabst.de", "city": "Düsseldorf",
     "postcode": "40235", "website": "https://www.motopabst.de", "country": "DE",
     "notes": "Hoffeldstr. 51"},
    {"name": "Niemann+Frey Krefeld", "email": "zentrale@niemann-frey.info", "city": "Krefeld",
     "postcode": "47829", "website": "http://niemann-frey.de", "country": "DE",
     "notes": "Adolf-Dembach-Str. 24"},
    {"name": "Road Star Motorcycles Fürth", "email": "info@roadstar-motorcycles.de",
     "city": "Fürth", "postcode": "90763", "website": "https://www.roadstar-motorcycles.de",
     "country": "DE", "notes": "Benno-Strauß-Straße 19"},
    {"name": "AMS Schweinfurt", "email": "info@ams-schweinfurt.de", "city": "Schweinfurt",
     "website": "https://ams-schweinfurt.de", "country": "DE", "notes": "Auto Motorrad Service"},
    {"name": "Fuhrberg Motorradtechnik", "email": "info@fmr-fuhrberg.de", "city": "Reutlingen",
     "postcode": "72762", "website": "https://fmr-fuhrberg.de", "country": "DE",
     "notes": "Reutlingen Motorradtechnik"},
    {"name": "Warm Up Aalen", "email": "info@warm-up.net", "city": "Aalen",
     "website": "https://www.triumph-ostalb.de", "country": "DE",
     "notes": "Triumph Ostalb / Motorradpartner"},
    {"name": "MW-Halle", "email": "service@mw-halle.de", "city": "Halle",
     "postcode": "06132", "website": "https://www.mw-halle.de", "country": "DE",
     "notes": "Pappelallee 1"},
    {"name": "Freijbike Halle", "email": "info@freijbike.de", "city": "Halle",
     "postcode": "06132", "website": "https://www.freijbike.de", "country": "DE",
     "notes": "Regensburger Str. 46"},
    {"name": "Motorrad Henkel Suhl", "email": "info@motorrad-henkel.de", "city": "Suhl",
     "website": "https://www.motorrad-henkel.de", "country": "DE", "notes": "Thüringen"},
    {"name": "Bike & Cars Jena", "email": "helbig@bikeandcars-jena.de", "city": "Jena",
     "website": "https://motorrad-jena.de", "country": "DE", "notes": "Jenas Biker Corner"},
    {"name": "KTM Erfurt (Zweirad Voss)", "email": "info@ktm-erfurt.de", "city": "Erfurt",
     "website": "https://ktm-erfurt.de", "country": "DE", "notes": "KTM dealer Erfurt"},
    {"name": "AHAG BMW Gelsenkirchen", "email": "info@ahag-bmw.de", "city": "Gelsenkirchen",
     "postcode": "45897", "website": "https://ahag-group.de", "country": "DE",
     "notes": "Kurt-Schumacher-Str. 382 — BMW Motorrad"},
    {"name": "Motorradtank Herne", "email": "info@motorradtank-herne.de", "city": "Herne",
     "postcode": "44625", "website": "", "country": "DE", "notes": "Bochumer Str. 178"},
    {"name": "Yamaha Zentrum Rhein-Ruhr West", "email": "info@yamaha-zentrum-west.de",
     "city": "Oberhausen", "postcode": "46049", "website": "https://yamaha-zentrum-west.de",
     "country": "DE", "notes": "Duisburger Str. 94"},
    {"name": "Motorradhaus Hoffmann Marl", "email": "info@motorrad-hoffmann.de",
     "city": "Marl", "website": "https://www.motorrad-hoffmann.de", "country": "DE",
     "notes": "Ruhrgebiet"},
    {"name": "Motorrad Warmuth Dessau", "email": "info@motorrad-warmuth.de",
     "city": "Dessau-Roßlau", "website": "https://ducati-mx.de", "country": "DE",
     "notes": "Ducati MX Dessau"},
    {"name": "Motorrad Kausche Görlitz", "email": "info@motorrad-kausche.de", "city": "Görlitz",
     "website": "", "country": "DE", "notes": "Sachsen-grens Polen"},

    # ===== Batch 13 (Feb 2026 — IT extra provincies) =====
    {"name": "Marcelli Moto Pesaro", "email": "commerciale@marcellimoto.com", "city": "Pesaro",
     "website": "https://marcellimoto.com", "country": "IT", "notes": "Marche - CFMOTO"},
    {"name": "Gabellini Moto Pesaro", "email": "gabellinimoto@libero.it", "city": "Pesaro",
     "website": "", "country": "IT", "notes": "Vogeitaly partner"},
    {"name": "CercarMoto Pavia", "email": "info@cercarmoto.com", "city": "Pavia",
     "website": "https://cercarmoto.com", "country": "IT", "notes": "Pavia moto"},
    {"name": "CMTmotor Como (Paoli)", "email": "como.paoli@cmtmotor.com", "city": "Como",
     "website": "https://www.cmtmotor.com/it-it/store-cmt/como-co-via-pasquale-paoli-61",
     "country": "IT", "notes": "Via Pasquale Paoli 61, Como"},
    {"name": "Stilmoto Sondrio", "email": "info@stilmotosondrio.com", "city": "Sondrio",
     "website": "https://stilmotosondrio.com", "country": "IT", "notes": "Sondrio"},
    {"name": "Pensini Moto Tirano", "email": "info@pensinimoto.com", "city": "Tirano",
     "website": "https://www.pensinimoto.com", "country": "IT", "notes": "Sondrio provincie"},
    {"name": "Supermotorace Cernusco", "email": "info@supermotorace.com",
     "city": "Cernusco Lombardone", "website": "https://www.supermotorace.com",
     "country": "IT", "notes": "Lecco provincie"},

    # ===== Batch 14 (Feb 2026 — FR + BE extra) =====
    {"name": "Heline Motos Saintes", "email": "helinemotos@wanadoo.fr", "city": "Saintes",
     "website": "https://heline-elite-motos-saintes-17.fr", "country": "FR",
     "notes": "Charente-Maritime"},
    {"name": "2D Moto Saintes", "email": "contact@2dmoto.fr", "city": "Saintes",
     "website": "https://www.2dmoto.fr", "country": "FR", "notes": "Charente-Maritime"},
    {"name": "BMW Motorrad Dupont Motos Orléans", "email": "contact2@dupont.net.bmw.fr",
     "city": "Olivet", "postcode": "45160", "website": "https://axxia.fr", "country": "FR",
     "notes": "876 rue de la Bergeresse — BMW Motorrad Loiret"},
    {"name": "BMW Motorrad Dupont Motos Montargis", "email": "contactmontargis@dupont.net.bmw.fr",
     "city": "Amilly", "postcode": "45200", "website": "https://axxia.fr", "country": "FR",
     "notes": "61 rue de la Rose Blanche"},
    # BE Antwerpen + Limburg extra
    {"name": "Cherry Motors Wilrijk", "email": "info@cherrymotors.be", "city": "Wilrijk",
     "website": "https://www.cherrymotors.be", "country": "BE", "notes": "Antwerpen-regio"},
    {"name": "ATT Racing Zwijndrecht", "email": "info@attracing.be", "city": "Zwijndrecht",
     "website": "https://www.attracing.be", "country": "BE", "notes": "Antwerpen-regio"},
    {"name": "Motohandel Geert Van Mol", "email": "info@geertvanmol.be", "city": "Melsele",
     "website": "https://www.geertvanmol.be", "country": "BE", "notes": "Groot-Antwerpen"},
    {"name": "Van Der Heyden Motors", "email": "info@vdheydenmotors.be", "city": "Antwerpen",
     "website": "https://www.vdheydenmotors.be", "country": "BE", "notes": "Antwerpen"},
    {"name": "Scooter Center Lommel", "email": "info@scootercenterlommel.be", "city": "Lommel",
     "postcode": "3920", "website": "https://www.scootercenterlommel.be", "country": "BE",
     "notes": "Luikersteenweg 454"},
    {"name": "Garage May Maaseik", "email": "info@garagemay.be", "city": "Maaseik",
     "website": "https://garagemay.be", "country": "BE", "notes": "Limburg"},
    {"name": "Motorhuis Limburg", "email": "info@motorhuislimburg.be", "city": "Limburg",
     "website": "https://www.motorhuislimburg.be", "country": "BE", "notes": "Limburg"},

    # ===== Batch 15 (Feb 2026 — extra rondes) =====
    {"name": "R+S Motorräder Saarbrücken", "email": "info@rs-motorraeder.de",
     "city": "Saarbrücken", "website": "https://www.rs-motorraeder.de", "country": "DE",
     "notes": "Saarbrücken Motorräder"},
    {"name": "Triumph Saarbrücken", "email": "info@triumphsb.de", "city": "Saarbrücken",
     "website": "https://www.triumphsaarbruecken.de", "country": "DE", "notes": "Triumph Saarland"},
    {"name": "Riller & Schnauck Berlin", "email": "kontakt@riller-schnauck.de",
     "city": "Berlin", "postcode": "12165", "website": "https://www.riller-schnauck.de",
     "country": "DE", "notes": "BMW Motorrad Berlin Charlottenburg + Marzahn"},
    # IT Sicilia extra
    {"name": "Superbike Trapani", "email": "superbiketp@libero.it", "city": "Trapani",
     "website": "https://moto.suzuki.it/dealer/96724", "country": "IT",
     "notes": "Via Partanna 13/15"},
    {"name": "Centro Moto Enna", "email": "centro.moto@alice.it", "city": "Enna",
     "website": "http://www.centromotoenna.it", "country": "IT", "notes": "Via Scifitello 2"},
    {"name": "Triumph Sicilia Siracusa", "email": "siracusa@triumphsicilia.it",
     "city": "Siracusa", "website": "https://www.triumphsicilia.it", "country": "IT",
     "notes": "Viale Tica 109"},
    # FR Limousin
    {"name": "Moto Move Limoges", "email": "info@motomove.fr", "city": "Limoges",
     "postcode": "87280", "website": "https://www.motomovegroupe.fr", "country": "FR",
     "notes": "Pole Moto Limoges - 9 Rue Pierre de Fermat"},
    # BE Vlaams-Brabant + Oost-Vlaanderen
    {"name": "Moto's Deschouwer Zemst", "email": "info@deschouwermotos.be", "city": "Zemst",
     "website": "https://deschouwermotos.be", "country": "BE", "notes": "Vlaams-Brabant"},
    {"name": "Revolution Motors Lembeek", "email": "info@revolutionmotors.be",
     "city": "Lembeek", "website": "https://revolutionmotors.be", "country": "BE",
     "notes": "Halle / Vlaams-Brabant"},
    {"name": "Scooter Point Aarschot", "email": "info@scooter-point.be", "city": "Aarschot",
     "website": "", "country": "BE", "notes": "Peugeot Motocycles Aarschot"},
    {"name": "Schockaert Motorservice Aalst", "email": "info@schockaertmotors.be",
     "city": "Aalst", "postcode": "9300", "website": "https://schockaertmotors.be",
     "country": "BE", "notes": "Lion d'orweg 13 — Oost-Vlaanderen"},

    # ===== Batch 16 (Feb 2026 — DE/IT/BE deep fill) =====
    {"name": "TurboMaxx Lübeck", "email": "info@turbomaxx.de", "city": "Lübeck",
     "website": "https://www.turbomaxx.de", "country": "DE", "notes": "Kawasaki-specialist"},
    {"name": "KBS Frankfurt", "email": "info@kbs-frankfurt.de", "city": "Frankfurt am Main",
     "postcode": "60314", "website": "http://www.kbs-frankfurt.de", "country": "DE",
     "notes": "Hanauer Landstraße 294"},
    {"name": "MoToRRAD in Dresden", "email": "info@motorradindresden.de", "city": "Dresden",
     "postcode": "01237", "website": "https://motorradindresden.de", "country": "DE",
     "notes": "Oskar-Röder-Str. 6"},
    {"name": "Suzuki Dresden (Autohaus Tross)", "email": "info@suzuki-dresden.de",
     "city": "Dresden", "website": "https://www.autohaus-tross.de", "country": "DE",
     "notes": "Suzuki dealer Dresden"},
    {"name": "Zweiradsport Meine", "email": "info@team-meine.de", "city": "Bayern/Norddt.",
     "website": "https://team-meine.de", "country": "DE", "notes": "Yamaha-Händler"},
    # IT Puglia
    {"name": "Mirto Moto", "email": "vendite@mirtomoto.it", "city": "Lecce",
     "website": "https://www.mirtomoto.it", "country": "IT",
     "notes": "Honda Lecce/Brindisi"},
    {"name": "Autotrend Taranto", "email": "info@autotrend.biz", "city": "Taranto",
     "website": "https://www.autotrend.it/sedi/taranto/", "country": "IT",
     "notes": "Multibrand Taranto"},
    {"name": "Mondo Moto Castellaneta", "email": "moto-moto@tiscali.it",
     "city": "Castellaneta", "website": "https://www.mondo-moto.it", "country": "IT",
     "notes": "Provincia Taranto"},
    # BE Luxembourg provincie
    {"name": "Aimery Racing", "email": "info@aimeryracing.be", "city": "Province Luxembourg",
     "website": "https://aimeryracing.be", "country": "BE", "notes": "Wallonie Luxembourg"},
    {"name": "Moto JL Sélection", "email": "parts@moto-jlselection.be", "city": "Wallonie",
     "website": "https://www.moto-jlselection.be", "country": "BE", "notes": "Pieces motos"},
    {"name": "Megabikes Bastogne", "email": "info@megabikes.be", "city": "Bastogne",
     "website": "", "country": "BE", "notes": "Province Luxembourg BE"},

    # ===== Batch 17 (Feb 2026 — IT Lombardia/Sicilia + DE) =====
    {"name": "RS Moto Bergamo", "email": "info@rsmoto.it", "city": "Bergamo",
     "website": "https://www.rsmoto.it", "country": "IT", "notes": "Bergamo moto dealer"},
    {"name": "Oldrati Moto Pedrengo", "email": "info@oldratimoto.it", "city": "Pedrengo",
     "website": "https://oldratimoto.it", "country": "IT", "notes": "Bergamo provincie"},
    {"name": "Triumph Brescia", "email": "info@triumphbrescia.it", "city": "Brescia",
     "website": "https://www.triumphbrescia.it", "country": "IT", "notes": "Triumph Brescia"},
    {"name": "Pancaldi Moto Montichiari", "email": "info@pancaldimoto.it",
     "city": "Montichiari", "website": "https://www.pancaldimoto.it", "country": "IT",
     "notes": "Brescia provincie"},
    {"name": "Valtermoto Group Seregno", "email": "info@valtermotogroup.com", "city": "Seregno",
     "website": "https://motomorinimonza.it", "country": "IT",
     "notes": "Moto Morini Monza/Brianza"},

    # ===== Batch 18 (Feb 2026 — DE Baden + NRW deep) =====
    {"name": "BMW Motorrad Bohling u. Eisele Karlsruhe", "email": "info@bohling-eisele.de",
     "city": "Karlsruhe", "website": "https://www.bmw-motorrad.de/bohling-eisele-karlsruhe",
     "country": "DE", "notes": "BMW Motorrad Karlsruhe"},
    {"name": "BMW Motorradcenter Heermann-Rhein", "email": "info@heermann-rhein-motorrad.de",
     "city": "Heilbronn", "website": "https://heermann-rhein-motorrad.de", "country": "DE",
     "notes": "BMW Motorrad Heilbronn"},
    {"name": "Zweirad Waibel Wiernsheim", "email": "info@zweiradwaibel.de",
     "city": "Wiernsheim-Pinache", "website": "https://www.zweiradwaibel.de", "country": "DE",
     "notes": "Pforzheim-regio"},
    {"name": "Bike Performance by Joachim Fegert", "email": "info@moto-nbg.de",
     "city": "Neuenbürg", "website": "https://www.moto-nbg.de", "country": "DE",
     "notes": "Pforzheim-regio"},
    {"name": "MZB Motorrad Bonn", "email": "info@motorradz.de", "city": "Bonn",
     "postcode": "53119", "website": "https://motorradhandel.suzuki.de/de/suzuki-haendler/361243",
     "country": "DE", "notes": "Dorotheenstr. 239 — Suzuki Bonn"},
    {"name": "EGM Motorrad Sven Gries", "email": "info@egm-motorrad.de", "city": "Bonn",
     "postcode": "53121", "website": "https://www.egm-motorrad.de", "country": "DE",
     "notes": "Wolfgang-Paul-Str. 5"},
    {"name": "Motorrad Peter Kaup Köln", "email": "post@motorrad-kaup.de", "city": "Köln",
     "postcode": "50827", "website": "https://motorrad-kaup.de", "country": "DE",
     "notes": "Vogelsanger Str. 350"},

    # ===== Batch 19 (Feb 2026 — meer rondes) =====
    {"name": "Limbächer Filderstadt", "email": "info@limbaecher.de", "city": "Filderstadt",
     "website": "https://www.limbaecher.de", "country": "DE",
     "notes": "Yamaha Stuttgart-regio"},
    {"name": "Zweirad Harder Konstanz", "email": "info@zweirad-harder.de", "city": "Konstanz",
     "website": "https://www.zweirad-harder.de", "country": "DE", "notes": "Konstanz"},
    {"name": "Auvergne Motos Aubière", "email": "nicolas@auvergne-motos.fr", "city": "Aubière",
     "website": "https://reseau.motoconcess.fr/auvergne-motos", "country": "FR",
     "notes": "Clermont-Ferrand regio"},
    {"name": "Elite Moto 15 Aurillac", "email": "contact@elitemoto15.com", "city": "Aurillac",
     "website": "https://elitemoto15.com", "country": "FR", "notes": "Auvergne / Cantal"},

    # ===== Batch 20 (Feb 2026 — 4 nieuwe regios) =====
    {"name": "Faieta Motors Pescara", "email": "abbigliamento@faietamoto.com",
     "city": "Pescara", "postcode": "65123", "website": "https://faietamotors.it",
     "country": "IT", "notes": "Via Nazionale Adriatica Nord 226"},
    {"name": "Starter Motos 71", "email": "olivier.startermotos@orange.fr",
     "city": "Varennes-lès-Mâcon", "website": "https://www.startermotos.fr",
     "country": "FR", "notes": "KTM/CFMOTO/Yamaha/GasGas dealer Bourgogne"},
    {"name": "Zweirad Center Gawelleck Ingolstadt", "email": "info@zweirad-in.de",
     "city": "Ingolstadt", "postcode": "85055", "website": "https://www.zweirad-in.de",
     "country": "DE", "notes": "Siemensstr. 7"},
    {"name": "Motoren Vandevelde", "email": "info@motorenvandevelde.be", "city": "Desselgem",
     "postcode": "8792", "website": "https://motorenvandevelde.be", "country": "BE",
     "notes": "Waregem-regio - Gentseweg 214"},

    # ===== Batch 21 (Feb 2026 — meer DE+IT+FR+BE) =====
    {"name": "FAR-Motor Wolfsburg-Fallersleben", "email": "info@far-motor.de",
     "city": "Wolfsburg-Fallersleben", "website": "https://www.far-motor.de",
     "country": "DE", "notes": "Wolfsburg"},
    {"name": "Motorrad Matthies Hildesheim", "email": "info@motorrad-matthies.de",
     "city": "Hildesheim", "website": "https://www.motorrad-matthies.de", "country": "DE",
     "notes": "Hildesheim motor dealer"},
    {"name": "Bräuer Motorradsport Emmerke", "email": "info@braeuer-motorradsport.de",
     "city": "Emmerke", "website": "https://www.braeuer-shop.de", "country": "DE",
     "notes": "Hildesheim regio"},
    {"name": "WELLER Premium Salzgitter", "email": "sz@wellergruppe.de", "city": "Salzgitter",
     "website": "https://wellergruppe.de/unternehmen/standorte/salzgitter", "country": "DE",
     "notes": "BMW Motorrad Salzgitter"},
    {"name": "RP Bike Liguria", "email": "info@rpbike.it", "city": "Liguria",
     "website": "https://www.wayel.it", "country": "IT", "notes": "Imperia provincie"},
    {"name": "Probike Loisirs Troyes", "email": "probike.loisirs@gmail.com",
     "city": "Pont Sainte Marie", "website": "https://www.cf-moto.fr/moto/concessionnaires/probike-loisirs",
     "country": "FR", "notes": "CFMOTO Troyes-regio"},
    {"name": "Sky Motos Châlons", "email": "skymotos@netcourrier.com",
     "city": "Châlons-en-Champagne", "website": "https://www.skymotos.fr",
     "country": "FR", "notes": "Sky Motos Marne"},
    {"name": "Francorchamps Motos Stavelot", "email": "info@francorchampsmotos.be",
     "city": "Stavelot", "website": "https://www.francorchampsmotos.be", "country": "BE",
     "notes": "Spa-Francorchamps regio - Kockelmann"},

    # ===== Batch 22 (Feb 2026 — laatste mega-batch) =====
    {"name": "Polidori Moto Prato", "email": "info@polidorimoto.it", "city": "Prato",
     "website": "https://www.polidorimoto.it", "country": "IT",
     "notes": "Honda/Piaggio/Aprilia/Suzuki/CFMOTO multibrand"},
    {"name": "Gruppo Bientinesi Livorno", "email": "storegalilei@gruppobientinesi.it",
     "city": "Livorno", "website": "https://www.gruppobientinesi.it", "country": "IT",
     "notes": "Kawasaki+Suzuki Livorno/Cecina"},
    {"name": "QJMOTOR Bordeaux", "email": "factorymoto@orange.fr", "city": "Mérignac",
     "postcode": "33700", "website": "https://qjmotor.fr/revendeurs", "country": "FR",
     "notes": "8 rue Johannes Gutenberg"},
    {"name": "QJMOTOR Périgueux", "email": "motoaxxeperigueux@gmail.com",
     "city": "Marsac sur l'Isle", "postcode": "24430", "website": "https://qjmotor.fr/revendeurs",
     "country": "FR", "notes": "Avenue Louis Suder"},
    {"name": "TC Moto Zaventem", "email": "info@tcmoto.be", "city": "Zaventem",
     "website": "https://www.tcmoto.be", "country": "BE",
     "notes": "Triumph Brussels/Mechelen/Tervuren/Haacht"},
    {"name": "ACB Brussels-Delta", "email": "aftersales.delta@acbrussels.be",
     "city": "Auderghem", "postcode": "1160", "website": "https://acb-group.be",
     "country": "BE", "notes": "Bd des Invalides 220"},

    # ===== Batch 23 (Feb 2026 — extra rondes) =====
    {"name": "E-moto Latina", "email": "info@e-moto.it", "city": "Latina",
     "website": "http://e-moto.it", "country": "IT", "notes": "Kawasaki Lazio"},
    {"name": "Werther Nice", "email": "info@werther.fr", "city": "Nice",
     "website": "https://www.motoservices.com", "country": "FR",
     "notes": "Côte d'Azur moto dealer"},
    {"name": "Cagnes Motors", "email": "contact@cagnesmotors.fr", "city": "Cagnes-sur-Mer",
     "website": "https://www.cagnesmotors.fr", "country": "FR",
     "notes": "Côte d'Azur 06"},
    {"name": "Garage Pieteraerens Geraardsbergen", "email": "info@pieteraerens.be",
     "city": "Geraardsbergen", "website": "https://www.garagepieteraerens.be",
     "country": "BE", "notes": "Moto Morini dealer Oost-Vlaanderen"},

    # ===== Batch 24 (Feb 2026 — DE Bayern + extra) =====
    {"name": "Motorrad Deutschmann Ansbach", "email": "info@motorrad-deutschmann.de",
     "city": "Ansbach", "postcode": "91522", "website": "http://www.motorrad-deutschmann.de",
     "country": "DE", "notes": "Am Fürstenweg 2"},
    {"name": "Cloppenburg Ansbach", "email": "info@cloppenburg-ansbach.de", "city": "Ansbach",
     "postcode": "91522", "website": "https://www.cloppenburg-gruppe.de/ansbach",
     "country": "DE", "notes": "BMW Motorrad - Rudolf-Diesel-Str. 2"},
    {"name": "Die Motorradfabrik Erlangen", "email": "info@die-motorradfabrik.de",
     "city": "Erlangen", "postcode": "91056", "website": "https://www.die-motorradfabrik.de",
     "country": "DE", "notes": "Frauenauracher Straße 61"},
    {"name": "Autohaus Schmack Hof", "email": "autohaus.schmack@schmack.de", "city": "Hof",
     "postcode": "95030", "website": "https://motorrad-schmack.de", "country": "DE",
     "notes": "Honda dealer Hof - Kulmbacher Str. 105"},

    # ===== Batch 25 (Feb 2026 — final round) =====
    {"name": "Dumke & Lütt Hamburg", "email": "info@dumke-luett.de", "city": "Hamburg",
     "website": "https://dumke-luett.de", "country": "DE",
     "notes": "Suzuki + Yamaha sinds 1976"},
    {"name": "Hamburg Motorcycle (Motowert)", "email": "info@motowert.de", "city": "Hamburg",
     "website": "https://motowert.de", "country": "DE",
     "notes": "Suzuki/Yamaha Hamburg"},
    {"name": "Elektronik Sachse Bremen", "email": "info@elektronik-sachse.de",
     "city": "Bremen", "postcode": "28213", "website": "https://www.elektronik-sachse.de",
     "country": "DE", "notes": "Bremen motor electronics+sales"},
    {"name": "Moto Nardi Macerata", "email": "info@motonardi.it", "city": "Macerata",
     "website": "https://www.motonardi.it", "country": "IT",
     "notes": "Suzuki Macerata/Ancona/Ascoli/Fermo"},

    # ===== Batch 26 (Feb 2026 — last DE round) =====
    {"name": "RK-Motorradshop Ludwigsburg", "email": "RK-Motorradshop@t-online.de",
     "city": "Ludwigsburg", "website": "https://rk-motorradshop.de", "country": "DE",
     "notes": "Ludwigsburg shop"},
    {"name": "Lorenz GmbH Ludwigsburg", "email": "info@zweirad-lorenz.de",
     "city": "Ludwigsburg", "website": "https://www.zweirad-lorenz.de", "country": "DE",
     "notes": "Zweirad Lorenz"},

    # ===== Batch 27 (Feb 2026 — Bodensee + Bavaria + Normandie) =====
    {"name": "Mahle Zweiräder Ravensburg", "email": "info@mahle-zweiraeder.de",
     "city": "Ravensburg", "website": "https://mahle-zweiraeder.de", "country": "DE",
     "notes": "BMW Motorrad Bodensee-regio"},
    {"name": "Zweiradwelt Ravensburg", "email": "info@zweiradwelt-ravensburg.de",
     "city": "Ravensburg", "website": "https://zweiradwelt-ravensburg.de", "country": "DE",
     "notes": "Ravensburg motor dealer"},
    {"name": "Alpenmove Garmisch", "email": "info@alpenmove.de", "city": "Garmisch-Partenkirchen",
     "website": "https://www.alpenmove.de", "country": "DE", "notes": "Segway & Motorrad Alpen"},
    {"name": "Motorrad Zeislmeier Wasserburg", "email": "mechaniker@zeislmeier.de",
     "city": "Wasserburg", "website": "https://www.motorrad-zeislmeier.de", "country": "DE",
     "notes": "Wasserburg/Inn"},
    {"name": "Rupp & Söhne Rosenheim", "email": "info@rupprosenheim.de", "city": "Rosenheim",
     "website": "https://www.rupp-rosenheim.de", "country": "DE", "notes": "Rosenheim dealer"},
    {"name": "Motorradwelt Auer", "email": "info@motorradwelt-auer.de", "city": "Bayern",
     "website": "https://www.motorradwelt-auer.de", "country": "DE", "notes": "Bavaria moto dealer"},
    {"name": "A.D. Pugliese BMW Motorrad Sicilia", "email": "usato.moto@adpugliese.bmw.it",
     "city": "Melilli", "website": "https://www.adpugliese.it", "country": "IT",
     "notes": "BMW Motorrad Caltanissetta/Ragusa/Agrigento"},
    {"name": "M2ROO Caen", "email": "contact@m2roo.fr", "city": "Cormelles-le-Royal",
     "website": "https://www.cf-moto.fr/moto/concessionnaires/m2roo", "country": "FR",
     "notes": "CFMOTO Caen Normandie"},

    # ===== Batch 28 (Feb 2026 — NRW + Centre-Val-de-Loire) =====
    {"name": "Triumph Köln Ost (Löhmer)", "email": "verkauf@motorrad-loehmer.de",
     "city": "Köln", "website": "https://triumph-koeln-ost.de", "country": "DE",
     "notes": "Triumph Köln Ost"},
    {"name": "BMW Motorrad Amplitude Motos Tours", "email": "contact-motos@amplitude.net.bmw.fr",
     "city": "Chambray-lès-Tours", "postcode": "37170", "website": "https://axxia.fr",
     "country": "FR", "notes": "66 rue Charles Coulomb"},
    {"name": "BMW Motorrad Panel Bourges", "email": "bourges@panel.net.bmw.fr",
     "city": "Saint-Doulchard", "postcode": "18230", "website": "https://axxia.fr",
     "country": "FR", "notes": "Rue des Creuzettes"},
    {"name": "BMW Motorrad Panel Châteauroux", "email": "chateauroux@panel.net.bmw.fr",
     "city": "Châteauroux", "postcode": "36000", "website": "https://axxia.fr",
     "country": "FR", "notes": "La Poterie Rocade Sud"},

    # ===== Batch 29 (Feb 2026 — laatste finale ronde) =====
    {"name": "Motorradbude Göttingen", "email": "info@motorradbude.de", "city": "Göttingen",
     "postcode": "37075", "website": "https://www.motorradbude.de", "country": "DE",
     "notes": "Hannoversche Str. 60"},
    {"name": "Zweiradteam Viole Göttingen", "email": "info@zweiradteam-viole.de",
     "city": "Göttingen", "postcode": "37079", "website": "https://www.zweiradteam-viole.de",
     "country": "DE", "notes": "Industriestr. 18"},
    {"name": "Sembenini Moto Trento", "email": "info@sembeninimotoverona.it",
     "city": "Trento", "website": "https://www.sembeninimoto.it", "country": "IT",
     "notes": "Trento/Verona moto"},
    {"name": "Trentino in Moto", "email": "info@trentinoinmoto.com", "city": "Trento",
     "website": "https://www.trentinoinmoto.it", "country": "IT", "notes": "CIO Trentino"},

    # ===== Batch 30 (Feb 2026 — final final) =====
    {"name": "Kosmoto Olbia", "email": "kosmoto1@libero.it", "city": "Olbia",
     "postcode": "07026", "website": "https://kosmoto-olbia-s-r-l.webnode.it",
     "country": "IT", "notes": "Honda Sardegna - Via D'Annunzio 67"},

    # ===== Batch 31 (Feb 2026 — Ostfriesland + PACA + Antwerpen-noord) =====
    {"name": "BMW Aurich (Tekken)", "email": "info@bmw-aurich.de", "city": "Aurich",
     "website": "https://tekken.de", "country": "DE", "notes": "BMW Motorrad Ostfriesland"},
    {"name": "Heiko Ihben Motorradhandel Aurich", "email": "info@motorrad-ihben.de",
     "city": "Aurich", "website": "https://www.motorrad-ihben.de", "country": "DE",
     "notes": "Aurich motor dealer"},
    {"name": "Lechner Kraftrad Emden", "email": "kontakt@lechner-kraftrad.de",
     "city": "Emden", "website": "https://www.lechner-kraftrad.de", "country": "DE",
     "notes": "Louis Emden service"},
    {"name": "RS Moto Group Udine (Triumph)", "email": "info@rsmotogroup.it", "city": "Udine",
     "website": "https://www.triumphudine.it", "country": "IT", "notes": "Triumph Udine"},
    {"name": "Sovrano Motos Cycles Marignane", "email": "sovrano-moto@wanadoo.fr",
     "city": "Marignane", "website": "https://sovrano-motoscycles.com", "country": "FR",
     "notes": "PACA Marignane"},
    {"name": "Salon Motors Salon-de-Provence", "email": "contact@salon-motors.com",
     "city": "Salon-de-Provence", "website": "https://salon-motors.fr", "country": "FR",
     "notes": "CFMOTO/Royal Enfield"},
    {"name": "Putse Scooters & Motoren Brasschaat", "email": "info@putsescooters.be",
     "city": "Brasschaat", "website": "https://www.putsescooters.be", "country": "BE",
     "notes": "Antwerpen-noord"},
    {"name": "Motors Thomas G. Stabroek", "email": "info@motorsthomas.be", "city": "Stabroek",
     "website": "https://www.motorsthomas.be", "country": "BE",
     "notes": "Honda+Yamaha Antwerpen-noord"},

    # ===== Batch 32 (Feb 2026 — Sachsen + IT Rome + BE Lokeren) =====
    {"name": "Yamaha Zentrum Leipzig (Müller)", "email": "yamaha@automobile-mueller.info",
     "city": "Leipzig", "postcode": "04328", "website": "https://www.yamaha-zentrum-leipzig.de",
     "country": "DE", "notes": "Schongauerstraße 31"},
    {"name": "Yamaha Service Leipzig", "email": "yamaha-service@automobile-mueller.info",
     "city": "Leipzig", "website": "https://www.automobile-mueller.info/yamaha-leipzig",
     "country": "DE", "notes": "Service-afdeling Müller"},
    {"name": "Gärtner's Motorradshop Dohna", "email": "info@gaertners-motorradshop.de",
     "city": "Dohna", "website": "https://www.gaertners-motorradshop.de", "country": "DE",
     "notes": "Yamaha Zentrum Dresdner Land"},
    {"name": "Link Motors Roma", "email": "info@linkmotors.it", "city": "Roma",
     "postcode": "00162", "website": "https://www.linkmotors.it", "country": "IT",
     "notes": "Piazza Carlo Magno 21"},
    {"name": "Interbike Lokeren", "email": "johan@interbike.be", "city": "Lokeren",
     "postcode": "9160", "website": "https://www.interbike.be", "country": "BE",
     "notes": "Dr. Vannestestraat 2"},

    # ===== Batch 33 (Feb 2026 — Brandenburg Yamaha) =====
    {"name": "Yamaha Nestler Neuenhagen", "email": "info@yamaha-nestler.de",
     "city": "Neuenhagen", "website": "https://yamaha-nestler.de", "country": "DE",
     "notes": "Yamaha Brandenburg"},
    {"name": "Bernards Motorrad Service", "email": "kontakt@bmsmotorrad.de",
     "city": "Berlin-Brandenburg", "website": "https://www.bernards-motorrad-service.de",
     "country": "DE", "notes": "Yamaha/Ducati Berlin-Brandenburg"},

    # ===== Batch 34 (Feb 2026 — Westfalen + Ducati Veneto + Champagne) =====
    {"name": "Motorrad Dahlhues Warendorf", "email": "info@motorraddahlhues.de",
     "city": "Warendorf", "website": "https://www.motorraddahlhues.de", "country": "DE",
     "notes": "Yamaha+Ducati Westfalen"},
    {"name": "Motorrad Weihe Ostwestfalen", "email": "info@motorrad-weihe.de",
     "city": "Ostwestfalen", "website": "https://www.motorrad-weihe.de", "country": "DE",
     "notes": "BMW+Yamaha grootste Ostwestfalen"},
    {"name": "Motorrad Zentrum Niederrhein", "email": "info@motorrad-zentrum-niederrhein.de",
     "city": "Niederrhein", "website": "https://motorrad-zentrum-niederrhein.de",
     "country": "DE", "notes": "Onderste Niederrhein"},
    {"name": "Moto-Kauf Dortmund", "email": "info@moto-kauf.de", "city": "Dortmund",
     "website": "https://moto-kauf.de", "country": "DE",
     "notes": "Suzuki+Yamaha motor-ankauf"},
    {"name": "Ducati Verona", "email": "info@ducativerona.com", "city": "Verona",
     "website": "https://www.ducati.com/it/it/concessionari/verona/ducati-verona",
     "country": "IT", "notes": "Ducati ufficiale Verona"},
    {"name": "Ducati Treviso (Villorba)", "email": "info@ducatitreviso.com",
     "city": "Lancenigo di Villorba", "website": "https://dealer.moto.it/ducatitreviso",
     "country": "IT", "notes": "Ducati ufficiale Treviso"},
    {"name": "Autovega Ducati Vicenza", "email": "info@autovega.com", "city": "Vicenza",
     "website": "https://www.autovega.com/ducati/", "country": "IT",
     "notes": "Ducati ufficiale Vicenza"},

    # ===== Batch 35 (Feb 2026 — IT Lombardia extra) =====
    {"name": "Motorama Bike Bergamo", "email": "info@motoramabike.it", "city": "Bergamo",
     "website": "https://www.motoramabike.it", "country": "IT", "notes": "Bergamo dealer"},
    {"name": "Victory Team Pavia", "email": "info@victoryteam.it", "city": "Pavia",
     "website": "https://victoryteam.it", "country": "IT", "notes": "Pavia moto"},

    # ===== Batch 36 (Feb 2026 — Harley-Davidson DE) =====
    {"name": "Thunderbike Harley-Davidson", "email": "info@thunderbike.de", "city": "Hamminkeln",
     "website": "https://www.thunderbike.de", "country": "DE",
     "notes": "Harley-Davidson + custom builds"},
    {"name": "Harley-Davidson Baden-Baden (Rick's)", "email": "info@hd-badenbaden.de",
     "city": "Baden-Baden", "website": "https://www.harleysite.de", "country": "DE",
     "notes": "Rick's Motorcycles"},

    # ===== Batch 37 (Feb 2026 — Final Suzuki IT) =====
    {"name": "Torino Moto SRL (Suzuki ufficiale)", "email": "info@torinomoto.com",
     "city": "Torino", "website": "https://www.suzuki.it/dealer/torinomoto",
     "country": "IT", "notes": "Suzuki concessionario ufficiale Torino"},

    # ===== Batch 38 (Feb 2026 — IT Milano + BE West-Vlaanderen) =====
    {"name": "S.N. Moto Milano", "email": "snmoto@libero.it", "city": "Milano",
     "website": "https://dealer.moto.it/snmoto", "country": "IT",
     "notes": "Via Tiraboschi 1 + Via Anfossi 32"},
    {"name": "Moto's Maes Ledegem", "email": "info@motosmaes.be", "city": "Ledegem",
     "website": "https://motosmaes.be/nl", "country": "BE",
     "notes": "Roeselare/Kortrijk-regio motorzaak"},

    # ===== Batch 39 (Feb 2026 — NL Brabant + IT BMW Motorrad ufficiali) =====
    {"name": "Swinkels Motoren Tilburg", "email": "info@swinkelsmotoren.nl", "city": "Tilburg",
     "postcode": "5046 GP", "website": "https://www.swinkelsmotoren.nl", "country": "NL",
     "notes": "Goirkestraat 106 — Yamaha occasions"},
    {"name": "Maestro Motors Tilburg", "email": "info@maestromotors.nl", "city": "Tilburg",
     "postcode": "5048 AB", "website": "https://maestromotors.nl", "country": "NL",
     "notes": "Kraaivenstraat 25-04"},
    {"name": "Van de Pol Motoren Helmond", "email": "vandepolmotoren@gmail.com",
     "city": "Helmond", "postcode": "5701 JG", "website": "https://www.vandepolmotoren.nl",
     "country": "NL", "notes": "Wolfstraat 74"},
    {"name": "DCA Motorcycles & EZS Sidecars Helmond", "email": "info@dcamotorcycles.nl",
     "city": "Helmond", "website": "https://www.dcamotorcycles.nl", "country": "NL",
     "notes": "Onderhoud + occasions + sidecars"},
    {"name": "Motorfelsinea BMW Motorrad Bologna", "email": "segreteria@bmwmotorradclubbologna.it",
     "city": "Bologna", "postcode": "40128", "website": "", "country": "IT",
     "notes": "Via della Liberazione 1"},
    {"name": "BMW Motorrad Club Firenze (Nova Moto)", "email": "info@bmwmotorradclubfirenze.it",
     "city": "Firenze", "postcode": "50127", "website": "", "country": "IT",
     "notes": "Via Stradivari 1/15"},
    {"name": "Baldassarre Moto BMW Bari", "email": "vittoria.giannoccaro@mb.conc-bmw.com",
     "city": "Bari", "postcode": "70124", "website": "", "country": "IT",
     "notes": "Via Niceforo 4/B"},
    {"name": "BMW Motorrad Club Catania (Nuova Sport Car)", "email": "info@bmwmotorradclubcatania.com",
     "city": "Catania", "postcode": "95100", "website": "", "country": "IT",
     "notes": "SS 192 km 81.700"},

    # ===== Batch 40 (Feb 2026 — Gelderland NL) =====
    {"name": "Premium Motors / ARN Motors Apeldoorn", "email": "info@arnmotors.nl",
     "city": "Apeldoorn", "website": "https://www.premiummotors.nl", "country": "NL",
     "notes": "150+ motor occasions Gelderland"},

    # ===== Batch 41 (Feb 2026 — NL Limburg + Overijssel) =====
    {"name": "MotoLeo Hoensbroek", "email": "info@motoleo.nl", "city": "Hoensbroek",
     "website": "https://www.motoleo.nl", "country": "NL",
     "notes": "Zuid-Limburg — 125 motoren showroom"},
    {"name": "Schepers Motoren Design", "email": "info@motorendesign.nl", "city": "Zuid-Limburg",
     "website": "https://motorendesign.nl", "country": "NL",
     "notes": "Mooie occasions Zuid-Limburg"},
    {"name": "Motor Centrum Almelo", "email": "info@motorcentrumalmelo.nl", "city": "Almelo",
     "postcode": "7605 AX", "website": "https://www.motorcentrumalmelo.nl", "country": "NL",
     "notes": "Rohofstraat 82"},

    # ===== Batch 42 (Feb 2026 — NL Utrecht regio) =====
    {"name": "HP Motoren Utrecht", "email": "info@hpmotoren.nl", "city": "Utrecht",
     "website": "https://hpmotoren.nl", "country": "NL",
     "notes": "Occasion motoren sinds 1996"},
    {"name": "De Jong Motoren", "email": "info@dejongmotoren.nl", "city": "Utrecht-regio",
     "website": "https://www.dejongmotoren.nl", "country": "NL",
     "notes": "In/verkoop occasions"},

    # ===== Batch 43 (Feb 2026 — IT Piaggio + BE Liège) =====
    {"name": "Arco Piaggio", "email": "info@arcopiaggio.it", "city": "Italia",
     "website": "https://arcopiaggio.it", "country": "IT",
     "notes": "Piaggio/Vespa/Aprilia concessionario ufficiale"},
    {"name": "MotoConti Milmort", "email": "info@moto-conti.be", "city": "Milmort",
     "website": "https://www.moto-conti.be", "country": "BE",
     "notes": "Liège-regio motor occasion"},
]


async def main():
    inserted = 0
    duplicates = 0
    skipped = 0
    now = datetime.now(timezone.utc).isoformat()

    for lead in WEB_SEARCH_LEADS:
        email = (lead.get("email") or "").strip().lower()
        if not email or not EMAIL_RE.match(email):
            skipped += 1
            print(f"  SKIP invalid email: {lead.get('name')} / {email}")
            continue
        existing = await db.taxatie_leads.find_one({"email_lower": email}, {"_id": 0, "id": 1})
        if existing:
            duplicates += 1
            print(f"  DUP {email}")
            continue
        doc = {
            "id": str(uuid.uuid4()),
            "name": lead.get("name") or "",
            "email": email,
            "email_lower": email,
            "address": lead.get("address") or "",
            "postcode": lead.get("postcode") or "",
            "city": lead.get("city") or "",
            "website": lead.get("website") or "",
            "country": lead.get("country") or "",
            "source_site": "web-search-feb2026",
            "source_url": "",
            "dealer_id": "",
            "status": "new",
            "notes": lead.get("notes") or "Gevonden via Google search (Feb 2026)",
            "sent_at": None,
            "batch_id": None,
            "created_at": now,
            "updated_at": now,
            "created_by": None,
        }
        await db.taxatie_leads.insert_one(doc)
        inserted += 1
        print(f"  ✅ {email} → {lead.get('name')}")

    print(f"\n=== TOTAAL: {inserted} nieuw · {duplicates} duplicaten · {skipped} skipped ===")
    by_country = {}
    for lead in WEB_SEARCH_LEADS:
        c = lead.get("country") or "?"
        by_country[c] = by_country.get(c, 0) + 1
    for c, n in sorted(by_country.items()):
        print(f"  {c}: {n}")


if __name__ == "__main__":
    asyncio.run(main())
